version: "3.8"
services:
    web:
        image: nginx:1.19.9-alpine
        ports:
            - 80:80
        volumes:
            - ./src:/var/www/html
            - ./default.conf:/etc/nginx/conf.d/default.conf
        links:
            - php
    php:
        image: php:8.0-fpm-alpine
        volumes:
            - ./src:/var/www/html