version: "3.8"
services:
    web:
        image: nginx:1.19.9-alpine
        container_name: nginx
        ports:
            - 80:80
        volumes:
            - ./src:/var/www/html
            - ./default.conf:/etc/nginx/conf.d/default.conf
        links:
            - php
    php:
        user: 1000:1000
        image: php:8.0-fpm-alpine
        container_name: php
        volumes:
            - ./src:/var/www/html
        env_file:
            - .env