version: "3.8"
services:
    web:
        image: nginx:1.19.9-alpine
        restart: unless-stopped
        container_name: nginx
        ports:
            - 80:80
        volumes:
            - ./src:/var/www/html
            - ./default.conf:/etc/nginx/conf.d/default.conf
        links:
            - php
        depends_on:
            - php
    php:
        build:
            context: ./images/php
        restart: unless-stopped
        container_name: php
        user: 1000:1000
        volumes:
            - ./src:/var/www/html
        env_file:
            - .env
        links:
            - db
        depends_on:
            - db
    db:
        image: library/mariadb:10.5-focal
        restart: unless-stopped
        container_name: database
        volumes:
            - ./database:/var/lib/mysql
        env_file:
            - .env